### ISSUE TITLE
EROFS: read-only file system

### ISSUE THREAD

**Issue by probonopd** [HR/Crypter#16]
Using the AppImage I get:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EROFS: read-only file system, mkdir '/tmp/.mount_ITKhd4/usr/bin/resources/app/script/debug'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:916:18)
    at Object.mkdirsSync (/tmp/.mount_ITKhd4/usr/bin/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
    at Object.<anonymous> (/tmp/.mount_ITKhd4/usr/bin/resources/app/script/logger.js:12:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
```

Please note that the AppImage itself is read-only, so if Crypter needs to write something it should use a directory in `$HOME`.

**Comment by HR** [comment]
Thanks for reporting this. That is a bug because it's writing the log files in the app source files directory when it should really write it in the appdata directory.

**Comment by HR** [comment]
@probonopd can you just verify that this has fixed it?

**Comment by probonopd** [comment]
.@HR can you provide a new AppImage for download?

**Comment by HR** [comment]
@probonopd I've updated the binaries https://github.com/HR/Crypter/releases/tag/v2.0.0

**Comment by probonopd** [comment]
Thanks, now it quits after entering the correct masterpass...

```
verbose: IPCMAIN: setMasterPass emitted Setting Masterpass...
verbose: IPCMAIN: Masterpass has been reset successfully
verbose: IPCMAIN: checkMasterPass emitted. Checking MasterPass...
info: IPCMAIN: PASSWORD MATCHES!
verbose: APP: window-all-closed event emitted
info: APP.ON('will-quit'): will-quit event emitted
info: APP: quit event emitted
info: win.closed event emitted for PromptWindow
info: win.closed event emitted for PromptWindow
```

**Comment by HR** [comment]
Which distro are you using? Can you delete the appdata and try again?

**Comment by probonopd** [comment]
Ubuntu 16.04. `rm -rf /home/me/.config/Crypter` did not change this.

**Comment by HR** [comment]
Fixed it with latest commit (and just verified it myself on ubuntu). Updated binaries available at https://github.com/HR/Crypter/releases/tag/v2.0.0
Should work on your end as well but if it still doesn't then please let me know. 
Happy crypting :)

**Comment by probonopd** [comment]
Thanks, I can confirm that it is working now.
