### ISSUE TITLE
Broken i32 AppImage

### ISSUE THREAD

**Issue by blackPantherOS** [HR/Crypter#19]
Hi, I tried 32bit AppImage and I get the following error:

`error: PROMISE ERR: LevelUPError: Failed to require LevelDOWN (/tmp/.mount_Wru5RE/usr/bin/resources/app/node_modules/leveldown/build/Release/leveldown.node: error ELF Class **ELFCLASS64)**.`

**Comment by HR** [comment]
@blackPantherOS Thanks for reporting the issue. This is a LevelDOWN compatibility issue . Please see https://github.com/HR/Crypter/issues/4
Can you try and use the 64bit version (Crypter-2.0.0-x86_64.AppImage) instead?

**Comment by blackPantherOS** [comment]
Okay, no problem and I can't try the system is x86 :)

**Comment by HR** [comment]
I'll remove the 32bit image. Future releases will use a more compatible persistent storage solution.
