### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by di48l069** [HR/Crypter#2]
Hi,

Is there any future updates to this application?

**Comment by HR** [comment]
Yes, I intend to keep this project alive. I've just been very busy lately but will work on this very soon. I have actually started implementing the decryption functionality in the dev branch. Check #1 out.
Once that has been implemented, Crypter version 2.0 will be released (https://github.com/HR/Crypter/milestones/v2.0).

You are welcome to contribute and suggest any ideas for version 2.0

**Comment by di48l069** [comment]
@HR I will do so

**Comment by HR** [comment]
Hi @di48l069 , just implemented the decryption functionality. Should ship more updates and finalise everything in coming days for 2.0
