### ISSUE TITLE
Installation .deb

### ISSUE THREAD

**Issue by di48l069** [HR/Crypter#3]
Hi @HR,

Please can you add the following for people that use Debian platform `crypter-{version}.deb`

With Installation guide inside Readme.md

**Debian Linux (Ubuntu)**

1. Download crypter-{version}.deb
2. Run `sudo dpkg --install crypter-{version}.deb` on the downloaded package.
3. Launch `crypter` using the installed `crypter` command.

**Comment by HR** [comment]
Hi @di48l069,
Thanks for raising this.
I'm going to actually implement a CI build process that will automatically build Crypter for all platforms for every new release. The releases will be signed as well. 
I'll also add the instructions.

In the interim, if you wanna add build instructions/script for debian platform then feel free to send a PR

**Comment by di48l069** [comment]
@HR Hi bud,

When will this be released? specifically for linux based systems

**Comment by di48l069** [comment]
@HR That's good news is there any hope for windows support?

**Comment by HR** [comment]
Yes. Since its electron, it can be built for windows. I'll get the ci build process setup up so that it automatically builds it for MacOS,Linux and Windows for every release (major & minor)

**Comment by di48l069** [comment]
@HR Sounds great cant wait to test

**Comment by HR** [comment]
@di48l069 I've released Crypter v2.0 as a [.nupkg](https://github.com/HR/Crypter/releases/tag/v2.0.0) for linux. Is that fine for you?

**Comment by di48l069** [comment]
@HR Looks good, glad you also brought out a windows edition
