### ISSUE TITLE
macOS Icon issue

### ISSUE THREAD

**Issue by joshua-s** [HR/Crypter#34]
In Crypter 3.0 on macOS Sierra, the icon is distorted slightly. This may be due to the way the drop shadow is added by the platform.

![untitled](https://cloud.githubusercontent.com/assets/1479244/26562520/cdd15a6c-4494-11e7-862d-a9d172ac2f71.jpeg)

**Comment by HR** [comment]
Looks fine on mine but will  🔍  👀 into it

**Comment by HR** [comment]
Can not reproduce the issue. Since no one else seems to be experiencing this issue, will close for now.
