### ISSUE TITLE
[Linux] desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [HR/Crypter#36]
desktop-file-validate says `crypter.desktop: error: value "Utility" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character`.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/266072264

(Link edited.)

**Comment by HR** [comment]
The reference link seems to be broken 😞 . Are you still experiencing this issue? Try [building](https://github.com/HR/Crypter#build) it on your machine.

**Comment by probonopd** [comment]
Fixed link. https://travis-ci.org/AppImage/appimage.github.io/builds/266072264
Building is not the issue, it's the invalid desktop file that is. Please run it through `desktop-file-validate` and make sure there are no errors reported, thanks.

**Comment by HR** [comment]
I do not have direct control over the Linux build process. Crypter uses electron build to build the bin. The category is declared at https://github.com/HR/Crypter/blob/dev/package.json#L62 so you can try adding a semi colon there.

**Comment by probonopd** [comment]
By using the latest version of electron-builder this should be fixed automatically. Please let me know once a new build is available on GitHub Releases using the latest version of electron-builder, then I can run it through the test again. Thank you very much.

**Comment by HR** [comment]
OK [Crypter v3.1](https://github.com/HR/Crypter/releases/tag/v3.1.0) is now available as a pre-release on GitHub. Let me know if it passes the test so I can make it official 😄 
Thanks for reporting this issue.

**Comment by probonopd** [comment]
Thanks, I confirm :+1:

**Comment by HR** [comment]
Awesome 😎
