### ISSUE TITLE
Encrypt folder ?

### ISSUE THREAD

**Issue by igithub1972** [HR/Crypter#37]
Hi, all's well when dropping a single file on the Crypter screen, but when I try to encrypt a folder, I get : 

> ERROR: EISDIR: illegal operation on a directory

When I drag&drop several files, only the first one is taken into account.
Why can't crypter handle these - common - cases ?

**Comment by HR** [comment]
Batch encryption and decryption is a WIP. You can track the  issue at https://github.com/HR/Crypter/issues/12.  Feel free to send a PR! :)

**Comment by HR** [comment]
However, you could zip the folder and then just run it through Crypter like any other file :)

**Comment by xxxjanus3** [comment]
I tried it. It is good as it control the size of the files . However, it
has issue reading the files and installation of files is not convenient

**Comment by HR** [comment]
I just tried it out using the `zip` archive format and it seems to be working fine. Anyways, it is a feature in works at https://github.com/HR/Crypter/issues/12.  Feel free to send a PR to speed it up! :)
