### ISSUE TITLE
False Positive? Hybrid Analysis / VirusTotal

### ISSUE THREAD

**Issue by antuketot76** [HR/Crypter#38]
### Prerequisites

* [Y] Can you reproduce the problem?
* [Y] Did you read the entire [README.md](https://github.com/HR/Crypter/blob/master/readme.md)?
* [Y] Did you read the [FAQs](https://github.com/HR/Crypter/blob/master/readme.md#faqs)?
* [Y] Do you fully understand how Crypter works and how to use it?
* [Y] Did you check the [issues](https://github.com/HR/Crypter/issues) to see if your bug or enhancement is already reported?

### FALSE POSITIVE? HYBRID ANALYSIS / VIRUS TOTAL

[AV/AM DETECTION ENGINE]

### Steps to Reproduce

1. [HYBRID ANALYSIS] [HERE](https://www.hybrid-analysis.com/sample/a69c21c5540393cd8b6d30356ca892738d60cc643474a54ec0819e5d08341df3/5aecb13c7ca3e15ef174bd1b)
![image](https://user-images.githubusercontent.com/33280865/39650231-4eaf7512-5022-11e8-94af-c98b4515785d.png)

2. [VIRUSTOTAL] [HERE](https://www.virustotal.com/#/file/a69c21c5540393cd8b6d30356ca892738d60cc643474a54ec0819e5d08341df3/detection)
![image](https://user-images.githubusercontent.com/33280865/39648768-5be74948-501e-11e8-95a3-e5f4d0a41e4e.png)

**Expected behavior:** [Shouldn't detect as malicious]

**Actual behavior:** [Suspicious Activity]

### 3.1.0.exe

SHA256 -  a69c21c5540393cd8b6d30356ca892738d60cc643474a54ec0819e5d08341df3 

Crypter:

Release (full release name): Crypter-Setup-3.1.0.exe

Operating System (name and version): WINDOW 7 64 BIT

You can find the full release name under https://github.com/HR/Crypter/releases. For version ```3.0.0``` and up, the version is found under ```Crypter > About``` or just in the menu ```Version X.Y.Z```.

**Comment by HR** [comment]
Not sure why it is marking it as malicious. Might be an [Electron](https://github.com/electron/electron) issue 🤔

**Comment by HR** [comment]
Closing because it's not a technical issue
