### ISSUE TITLE
Hide my poject / execute my project

### ISSUE THREAD

**Issue by joker8989** [HR/Crypter#40]
Have not read the README yet but it looks good i will try it very soon..
Sorry for the stupid question but your project only encrypts the files? Or i can execute my file as well? I mean if i have a project i created and i dont want to people be able to read the code but still able to execute it... :)
Which is it?

Thankx for your time anyway

**Comment by HR** [comment]
Encrypted code can't be executed. It has to be machine-readable which can be [reverse engineered](https://en.wikipedia.org/wiki/Reverse_engineering) and read by humans.

What you want is to [obfuscate](https://en.wikipedia.org/wiki/Obfuscation_(software)) your code but you should know that there is no way that guarantees 100% unreadability.

If you are using a compiled language then you already get a level of obfuscation by _compiling_ your code. There is plenty of open source obfuscation software that you can use to obfuscate your code.
