### ISSUE TITLE
Is at EOL?

### ISSUE THREAD

**Issue by abbylyra** [HR/Crypter#64]
This hasn't been updated in 2 years, shouldn't this be archived?

**Comment by HR** [comment]
Hey @crownalexanraven, yeah I've not had the time to continue developing this and there haven't been any new feature request so will probably archive it. 

@crownalexanraven are you still actively using this?

**Comment by abbylyra** [comment]
negative, just wanted to know.
i'm not smart enough to update it so i wanted to know.
Good work though :)
